### ISSUE TITLE
Write Github action to merge master to all branches

### ISSUE THREAD

**Issue by michaell4438** [XaverianTeamRobotics/CenterstageFTCrobotcontroller#519]

**Comment by MatthewL246** [comment]
So basically: on each new commit to master, merge master with the other branches to keep them up-to-date.

**Comment by michaell4438** [comment]
Yes. But don't do all branches, have a list of branches which we can delete from or add to

**Comment by MatthewL246** [comment]
Alright. Which ones should it start with?

**Comment by michaell4438** [comment]
Mine and Colin's

**Comment by MatthewL246** [comment]
I made it, and it seems like it works [(second try)](https://github.com/XaverianTeamRobotics/FtcRobotController/actions/runs/6277482737/job/17049327389)

**Comment by MatthewL246** [comment]
Huh why is it jammed on "Post checkout repository," that's weird?
