### ISSUE TITLE
Changes to the controls of our robot

### ISSUE THREAD

**Issue by michaell4438** [XaverianTeamRobotics/CenterstageFTCrobotcontroller#541]
This is an open-ended "challenge" for the programmers. We have a problem. The controls of our features are hard to manage, and we need to manually make sure they do not conflict.

We need the ability for Features to have fields that store what buttons or axes correspond to an action and to have a method that OpModes can use to change any conflicting controls, as well as changes to the `registerFeature` that can check for conflicting controls upon adding the Feature.

There should be a "middleman" method between the Feature trying to read a button and the button being read, with this "middleman" method using a list of controls to say which action requires which button.

Optionally, add an additional optional parameter to allow for bypassing duplicate control checks.

I will use this as somewhat of a learning exercise and I will be willing to walk you through how to solve the problem. Feel free to add a comment with questions or link a PR. Please don't merge PRs for this issue without my approval.

**Comment by MatthewL246** [comment]
I had a crazy idea on this. What if features could define actions and then the opmode would bind them to a button, like in a video game with keybindings?

`ExFeature.java`
```java
public class ExFeature extends Feature {
    public void doSomething(boolean buttonPressed) {
        if (buttonPressed) servo.doSomething();
    }

    public void runMotor(int axis) {
        motor0.setPower(axis);
    }
}
```

`ExOpmode.java`
```java
public class ExOpmode extends OperationMode implements TeleOperation {
    public void construct() {
        ExFeature feature = new ExFeature();
        feature.bind(controller1.buttonA, doSomething);
        feature.bind(controller1.leftStickY, runMotor);
        registerFeature(feature);
    }

    public void run() {}
}
```

But IDK how that would even work.

**Comment by michaell4438** [comment]
That might not work because you would have to do some complicated reflection. I think what we need is a "middleman" accessor for the controllers, so instead of doing literally `controller1.getButtonA()` you do something like `getButton(ACTION_ID)` where `ACTION_ID` would be some constant stored in the feature, and it returns the value of whichever button/axis is bound. If you find the way you outlined does work then that might be a better way.

**Comment by michaell4438** [comment]
Also @24cteahan can you update us on your progress?
