### ISSUE TITLE
Work on the automatic autonomous

### ISSUE THREAD

**Issue by michaell4438** [XaverianTeamRobotics/CenterstageFTCrobotcontroller#597]
So this is something that I want people's help with.

For the autonomous, this year I want to make something which I call the **_Auto Auto Creator_**, which will be capable of automatically creating an autonomous route given some parameters [(see AutoAutoCreatorConfig)](https://github.com/XaverianTeamRobotics/FtcRobotController/blob/feature/auto-auto/TeamCode/src/main/java/org/firstinspires/ftc/teamcode/internals/motion/auto_auto/AutoAutoCreatorConfig.java).

This would stitch together a bunch of paths based on what we specified in the parameters and score pixels when it needed to, park, etc.

Currently what needs to get done is:
 - Creating the list of path segments
 - Creating an algorithm for navigating using those path segments
 - Making the robot not navigate to places where it could hit something

If anyone wants to help (this is open to everybody, even the less experienced) please let me know so I can teach you about the frameworks that we use for the auto navigation.

**Comment by lfeeney25** [comment]
I would like to help
